version: "3.9"

services:
  airflow-webserver:
    build: .
    restart: unless-stopped
    env_file: .env
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=${AIRFLOW_DATABASE_CONN}
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./booksscraper:/opt/booksscraper
      - ./spider_dbt:/opt/spider_dbt
    ports:
      - "8080:8080"
    command: >
      bash -c "airflow db init &&
      airflow users create -u admin -p admin -f Admin -l User -r Admin -e admin@example.com || true &&
      airflow webserver"

  airflow-scheduler:
    build: .
    restart: unless-stopped
    env_file: .env
    depends_on:
      - airflow-webserver
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=${AIRFLOW_DATABASE_CONN}
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./booksscraper:/opt/booksscraper
      - ./spider_dbt:/opt/spider_dbt
    command: scheduler



