version: '3'
services:
  scrapy:
    build: .
    container_name: scrapy_container
    volumes:
      - .:/usr/src/app  # Map the project folder
      - ./data:/data  # Map the local ./data folder to /data inside the container
    working_dir: /usr/src/app  # Working directory where your Scrapy project is
    command: ./run_spiders.sh  # Command to start the spiders
    depends_on:
      - db

  db:
    image: nouchka/sqlite3  # SQLite database container
    container_name: sqlite_db




